apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea-demo
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea-demo
  template:
    metadata:
      labels:
        app: servicea-demo
    spec:
      initContainers:
      - name: download-otel-agent
        image: busybox:latest
        command: ['sh', '-c', 'wget -O /otel/otel-java-agent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.30.0/opentelemetry-javaagent.jar']
        volumeMounts:
        - name: otel-agent
          mountPath: /otel
      containers:
      - name: servicea
        image: mayupdocker/servicea-demo:latest
        ports:
        - containerPort: 8080        
        volumeMounts:
        - name: otel-agent
          mountPath: /otel
      volumes:
      - name: otel-agent
        emptyDir: {}
